### ISSUE TITLE
Add connection type support

### ISSUE THREAD

**Issue by whirvis** [BlockServerProject/JRakLib#5]
~~This is not a bug, but rather a feature request.~~

~~You see, I have added a feature to my API, JRakNet, that allows for the user to get the protocol implementation when their server is pinged, they discover a server, when they connect to a server, or when a client connects to them. The way this works is by appending a sequence of magic bytes at the end of packets that would be needed to accomplish this (Which is only 4) and when receiving said packets seeing if there is enough data to check the magic header and ID byte. The current ID's in JRakNet mean the following:~

~~- ID 0: Vanilla (Official RakNet client/server)~~
~~- ID 1: [JRakNet](https://github.com/JRakNet/JRakNet)~~
~~- ID 2: [RakLib](https://github.com/pmmp/RakLib)~~
~~- ID 3: [JRakLib+](https://github.com/jython234/JRakLibPlus)~~

~~The code needed to accomplish this can be found in this [commit](https://github.com/JRakNet/JRakNet/commit/9ada391ba0a34b4967795a2db131e7618f369ae3). Whether or not you want to have this feature is of course up to you, and if you want me to code it in myself I would be happy to do a pull request! :D~~

~~Thanks! -Whirvis~~

The fork for the code to do this has been deleted, as the code to accomplish this feature has been rewritten out of necessity.

**Comment by alejzeis** [comment]
Currently I'm not really working on this project much more, but if you want
to you can create a pull request and I'll review it and merge it. It would
be a good help to.

**Comment by whirvis** [comment]
@jython234 Thanks! I'm assuming this goes for JRakLibPlus as well?

**Comment by alejzeis** [comment]
Yeah, if you had to have a priority I would prefer jraklibplus get it first
as it is what I think is the more advanced of the two as this is just a
direct port from the PHP version.

**Comment by whirvis** [comment]
I realized that JRakLib was stuck on protocol 7, and not 8, meaning it could not connect to any servers. I'm going to only add this support for JRakLibPlus, as me adding it to JRakLib would be completely meaningless.

I found that out the hard way after spending an hour on coding the functionality D:

**Comment by alejzeis** [comment]
Makes sense, yeah I stopped updating JRakLib a while back.

**Comment by whirvis** [comment]
I'm making progress on the JRakLibPlus feature! However I was thinking, should I use an ID system or just use Strings for the connection types? Because if we used ID's then it would be really hard to list your implementation as all versions of it had to have your ID, but if we used strings as long as the implementation had support it would work!

**Comment by whirvis** [comment]
I found a glitch in the OpenConnectionRequest2Packet class, in the decode you are using an unsigned short to get the client ID instead of reading a long

**Comment by alejzeis** [comment]
I think ID is the best choice as to reduce overhead as much as possible. Also, doesn't official raknet drop packets which have extra bytes, which would cause problems for this?

**Comment by whirvis** [comment]
Well this is setup so RakNet does not have to change at all, this works by adding a few extra bytes at the end of UnconnectedPing, UnconnectedPong, OpenConnectionRequestTwo, and OpenConnectionResponseTwo. As long as your API implementation does not drop extra bytes it should not be a problem. What I think will do is add a note in the documentation that says to message me if you want your implementation listed and I'll make forks for all the other implementations that are listed. Does that sound good?

**Comment by alejzeis** [comment]
I guess as long as vanilla raknet still works with those extra bytes.

**Comment by whirvis** [comment]
Vanilla RakNet is not affected by it at all :)
I have also finished the pull request! :D

**Comment by alejzeis** [comment]
Sounds good then.
